//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFClient.TicketBookingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="TicketBookingServiceReference.TicketBooking")]
    public interface TicketBooking {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/registerRequest", ReplyAction="http://ws/TicketBooking/registerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFClient.TicketBookingServiceReference.registerResponse register(WPFClient.TicketBookingServiceReference.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/registerRequest", ReplyAction="http://ws/TicketBooking/registerResponse")]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.registerResponse> registerAsync(WPFClient.TicketBookingServiceReference.registerRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/findFlightsBetweenGivenCitiesRequest", ReplyAction="http://ws/TicketBooking/findFlightsBetweenGivenCitiesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesResponse findFlightsBetweenGivenCities(WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/findFlightsBetweenGivenCitiesRequest", ReplyAction="http://ws/TicketBooking/findFlightsBetweenGivenCitiesResponse")]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesResponse> findFlightsBetweenGivenCitiesAsync(WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/checkReservationRequest", ReplyAction="http://ws/TicketBooking/checkReservationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFClient.TicketBookingServiceReference.checkReservationResponse checkReservation(WPFClient.TicketBookingServiceReference.checkReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/checkReservationRequest", ReplyAction="http://ws/TicketBooking/checkReservationResponse")]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.checkReservationResponse> checkReservationAsync(WPFClient.TicketBookingServiceReference.checkReservationRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/BookFlightRequest", ReplyAction="http://ws/TicketBooking/BookFlightResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFClient.TicketBookingServiceReference.BookFlightResponse BookFlight(WPFClient.TicketBookingServiceReference.BookFlightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/BookFlightRequest", ReplyAction="http://ws/TicketBooking/BookFlightResponse")]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.BookFlightResponse> BookFlightAsync(WPFClient.TicketBookingServiceReference.BookFlightRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/loginRequest", ReplyAction="http://ws/TicketBooking/loginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFClient.TicketBookingServiceReference.loginResponse login(WPFClient.TicketBookingServiceReference.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/loginRequest", ReplyAction="http://ws/TicketBooking/loginResponse")]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.loginResponse> loginAsync(WPFClient.TicketBookingServiceReference.loginRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/getAllFlightRequest", ReplyAction="http://ws/TicketBooking/getAllFlightResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFClient.TicketBookingServiceReference.getAllFlightResponse getAllFlight(WPFClient.TicketBookingServiceReference.getAllFlightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/getAllFlightRequest", ReplyAction="http://ws/TicketBooking/getAllFlightResponse")]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.getAllFlightResponse> getAllFlightAsync(WPFClient.TicketBookingServiceReference.getAllFlightRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/findAllCountriesToWhichPlanesDepartFromAgivenCityRequest", ReplyAction="http://ws/TicketBooking/findAllCountriesToWhichPlanesDepartFromAgivenCityResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityResponse findAllCountriesToWhichPlanesDepartFromAgivenCity(WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/findAllCountriesToWhichPlanesDepartFromAgivenCityRequest", ReplyAction="http://ws/TicketBooking/findAllCountriesToWhichPlanesDepartFromAgivenCityResponse" +
            "")]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityResponse> findAllCountriesToWhichPlanesDepartFromAgivenCityAsync(WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/findAirPortByCityRequest", ReplyAction="http://ws/TicketBooking/findAirPortByCityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFClient.TicketBookingServiceReference.findAirPortByCityResponse findAirPortByCity(WPFClient.TicketBookingServiceReference.findAirPortByCityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/findAirPortByCityRequest", ReplyAction="http://ws/TicketBooking/findAirPortByCityResponse")]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findAirPortByCityResponse> findAirPortByCityAsync(WPFClient.TicketBookingServiceReference.findAirPortByCityRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/findAirPortByCountryRequest", ReplyAction="http://ws/TicketBooking/findAirPortByCountryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFClient.TicketBookingServiceReference.findAirPortByCountryResponse findAirPortByCountry(WPFClient.TicketBookingServiceReference.findAirPortByCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/findAirPortByCountryRequest", ReplyAction="http://ws/TicketBooking/findAirPortByCountryResponse")]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findAirPortByCountryResponse> findAirPortByCountryAsync(WPFClient.TicketBookingServiceReference.findAirPortByCountryRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/findAllTheCountriesThatPlanesDepartFromRequest", ReplyAction="http://ws/TicketBooking/findAllTheCountriesThatPlanesDepartFromResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromResponse findAllTheCountriesThatPlanesDepartFrom(WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/TicketBooking/findAllTheCountriesThatPlanesDepartFromRequest", ReplyAction="http://ws/TicketBooking/findAllTheCountriesThatPlanesDepartFromResponse")]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromResponse> findAllTheCountriesThatPlanesDepartFromAsync(WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class passenger : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string surnameField;
        
        private string emailField;
        
        private string loginField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class cityDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class countryDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private cityDTO[] citiesListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citiesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public cityDTO[] citiesList {
            get {
                return this.citiesListField;
            }
            set {
                this.citiesListField = value;
                this.RaisePropertyChanged("citiesList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class passengerDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string surnameField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class ticket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private flight flightField;
        
        private passengerDTO passengerField;
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public flight flight {
            get {
                return this.flightField;
            }
            set {
                this.flightField = value;
                this.RaisePropertyChanged("flight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public passengerDTO passenger {
            get {
                return this.passengerField;
            }
            set {
                this.passengerField = value;
                this.RaisePropertyChanged("passenger");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
                this.RaisePropertyChanged("codeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class flight : object, System.ComponentModel.INotifyPropertyChanged {
        
        private airport to_AirPortField;
        
        private airport from_AirPortField;
        
        private string flightDateField;
        
        private int priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public airport to_AirPort {
            get {
                return this.to_AirPortField;
            }
            set {
                this.to_AirPortField = value;
                this.RaisePropertyChanged("to_AirPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public airport from_AirPort {
            get {
                return this.from_AirPortField;
            }
            set {
                this.from_AirPortField = value;
                this.RaisePropertyChanged("from_AirPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string flightDate {
            get {
                return this.flightDateField;
            }
            set {
                this.flightDateField = value;
                this.RaisePropertyChanged("flightDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class airport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string cityField;
        
        private string nameField;
        
        private string streetField;
        
        private int numer_of_buildingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numer_of_building {
            get {
                return this.numer_of_buildingField;
            }
            set {
                this.numer_of_buildingField = value;
                this.RaisePropertyChanged("numer_of_building");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class registerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFClient.TicketBookingServiceReference.passenger arg0;
        
        public registerRequest() {
        }
        
        public registerRequest(WPFClient.TicketBookingServiceReference.passenger arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class registerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public registerResponse() {
        }
        
        public registerResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findFlightsBetweenGivenCities", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class findFlightsBetweenGivenCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        public findFlightsBetweenGivenCitiesRequest() {
        }
        
        public findFlightsBetweenGivenCitiesRequest(string arg0, string arg1, string arg2, string arg3, string arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findFlightsBetweenGivenCitiesResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class findFlightsBetweenGivenCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFClient.TicketBookingServiceReference.flight[] @return;
        
        public findFlightsBetweenGivenCitiesResponse() {
        }
        
        public findFlightsBetweenGivenCitiesResponse(WPFClient.TicketBookingServiceReference.flight[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkReservation", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class checkReservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public checkReservationRequest() {
        }
        
        public checkReservationRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkReservationResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class checkReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFClient.TicketBookingServiceReference.ticket @return;
        
        public checkReservationResponse() {
        }
        
        public checkReservationResponse(WPFClient.TicketBookingServiceReference.ticket @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookFlight", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class BookFlightRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFClient.TicketBookingServiceReference.flight arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFClient.TicketBookingServiceReference.passengerDTO arg1;
        
        public BookFlightRequest() {
        }
        
        public BookFlightRequest(WPFClient.TicketBookingServiceReference.flight arg0, WPFClient.TicketBookingServiceReference.passengerDTO arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookFlightResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class BookFlightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFClient.TicketBookingServiceReference.ticket @return;
        
        public BookFlightResponse() {
        }
        
        public BookFlightResponse(WPFClient.TicketBookingServiceReference.ticket @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public loginRequest() {
        }
        
        public loginRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFClient.TicketBookingServiceReference.passengerDTO @return;
        
        public loginResponse() {
        }
        
        public loginResponse(WPFClient.TicketBookingServiceReference.passengerDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllFlight", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getAllFlightRequest {
        
        public getAllFlightRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllFlightResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getAllFlightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFClient.TicketBookingServiceReference.flight[] @return;
        
        public getAllFlightResponse() {
        }
        
        public getAllFlightResponse(WPFClient.TicketBookingServiceReference.flight[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllCountriesToWhichPlanesDepartFromAgivenCity", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class findAllCountriesToWhichPlanesDepartFromAgivenCityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public findAllCountriesToWhichPlanesDepartFromAgivenCityRequest() {
        }
        
        public findAllCountriesToWhichPlanesDepartFromAgivenCityRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllCountriesToWhichPlanesDepartFromAgivenCityResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class findAllCountriesToWhichPlanesDepartFromAgivenCityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFClient.TicketBookingServiceReference.countryDTO[] @return;
        
        public findAllCountriesToWhichPlanesDepartFromAgivenCityResponse() {
        }
        
        public findAllCountriesToWhichPlanesDepartFromAgivenCityResponse(WPFClient.TicketBookingServiceReference.countryDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAirPortByCity", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class findAirPortByCityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public findAirPortByCityRequest() {
        }
        
        public findAirPortByCityRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAirPortByCityResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class findAirPortByCityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFClient.TicketBookingServiceReference.airport[] @return;
        
        public findAirPortByCityResponse() {
        }
        
        public findAirPortByCityResponse(WPFClient.TicketBookingServiceReference.airport[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAirPortByCountry", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class findAirPortByCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public findAirPortByCountryRequest() {
        }
        
        public findAirPortByCountryRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAirPortByCountryResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class findAirPortByCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFClient.TicketBookingServiceReference.airport[] @return;
        
        public findAirPortByCountryResponse() {
        }
        
        public findAirPortByCountryResponse(WPFClient.TicketBookingServiceReference.airport[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllTheCountriesThatPlanesDepartFrom", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class findAllTheCountriesThatPlanesDepartFromRequest {
        
        public findAllTheCountriesThatPlanesDepartFromRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllTheCountriesThatPlanesDepartFromResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class findAllTheCountriesThatPlanesDepartFromResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WPFClient.TicketBookingServiceReference.countryDTO[] @return;
        
        public findAllTheCountriesThatPlanesDepartFromResponse() {
        }
        
        public findAllTheCountriesThatPlanesDepartFromResponse(WPFClient.TicketBookingServiceReference.countryDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TicketBookingChannel : WPFClient.TicketBookingServiceReference.TicketBooking, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TicketBookingClient : System.ServiceModel.ClientBase<WPFClient.TicketBookingServiceReference.TicketBooking>, WPFClient.TicketBookingServiceReference.TicketBooking {
        
        public TicketBookingClient() {
        }
        
        public TicketBookingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TicketBookingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketBookingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketBookingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFClient.TicketBookingServiceReference.registerResponse WPFClient.TicketBookingServiceReference.TicketBooking.register(WPFClient.TicketBookingServiceReference.registerRequest request) {
            return base.Channel.register(request);
        }
        
        public bool register(WPFClient.TicketBookingServiceReference.passenger arg0) {
            WPFClient.TicketBookingServiceReference.registerRequest inValue = new WPFClient.TicketBookingServiceReference.registerRequest();
            inValue.arg0 = arg0;
            WPFClient.TicketBookingServiceReference.registerResponse retVal = ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).register(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.registerResponse> WPFClient.TicketBookingServiceReference.TicketBooking.registerAsync(WPFClient.TicketBookingServiceReference.registerRequest request) {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.registerResponse> registerAsync(WPFClient.TicketBookingServiceReference.passenger arg0) {
            WPFClient.TicketBookingServiceReference.registerRequest inValue = new WPFClient.TicketBookingServiceReference.registerRequest();
            inValue.arg0 = arg0;
            return ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).registerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesResponse WPFClient.TicketBookingServiceReference.TicketBooking.findFlightsBetweenGivenCities(WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesRequest request) {
            return base.Channel.findFlightsBetweenGivenCities(request);
        }
        
        public WPFClient.TicketBookingServiceReference.flight[] findFlightsBetweenGivenCities(string arg0, string arg1, string arg2, string arg3, string arg4) {
            WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesRequest inValue = new WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesResponse retVal = ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).findFlightsBetweenGivenCities(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesResponse> WPFClient.TicketBookingServiceReference.TicketBooking.findFlightsBetweenGivenCitiesAsync(WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesRequest request) {
            return base.Channel.findFlightsBetweenGivenCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesResponse> findFlightsBetweenGivenCitiesAsync(string arg0, string arg1, string arg2, string arg3, string arg4) {
            WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesRequest inValue = new WPFClient.TicketBookingServiceReference.findFlightsBetweenGivenCitiesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            return ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).findFlightsBetweenGivenCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFClient.TicketBookingServiceReference.checkReservationResponse WPFClient.TicketBookingServiceReference.TicketBooking.checkReservation(WPFClient.TicketBookingServiceReference.checkReservationRequest request) {
            return base.Channel.checkReservation(request);
        }
        
        public WPFClient.TicketBookingServiceReference.ticket checkReservation(int arg0) {
            WPFClient.TicketBookingServiceReference.checkReservationRequest inValue = new WPFClient.TicketBookingServiceReference.checkReservationRequest();
            inValue.arg0 = arg0;
            WPFClient.TicketBookingServiceReference.checkReservationResponse retVal = ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).checkReservation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.checkReservationResponse> WPFClient.TicketBookingServiceReference.TicketBooking.checkReservationAsync(WPFClient.TicketBookingServiceReference.checkReservationRequest request) {
            return base.Channel.checkReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.checkReservationResponse> checkReservationAsync(int arg0) {
            WPFClient.TicketBookingServiceReference.checkReservationRequest inValue = new WPFClient.TicketBookingServiceReference.checkReservationRequest();
            inValue.arg0 = arg0;
            return ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).checkReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFClient.TicketBookingServiceReference.BookFlightResponse WPFClient.TicketBookingServiceReference.TicketBooking.BookFlight(WPFClient.TicketBookingServiceReference.BookFlightRequest request) {
            return base.Channel.BookFlight(request);
        }
        
        public WPFClient.TicketBookingServiceReference.ticket BookFlight(WPFClient.TicketBookingServiceReference.flight arg0, WPFClient.TicketBookingServiceReference.passengerDTO arg1) {
            WPFClient.TicketBookingServiceReference.BookFlightRequest inValue = new WPFClient.TicketBookingServiceReference.BookFlightRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WPFClient.TicketBookingServiceReference.BookFlightResponse retVal = ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).BookFlight(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.BookFlightResponse> WPFClient.TicketBookingServiceReference.TicketBooking.BookFlightAsync(WPFClient.TicketBookingServiceReference.BookFlightRequest request) {
            return base.Channel.BookFlightAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.BookFlightResponse> BookFlightAsync(WPFClient.TicketBookingServiceReference.flight arg0, WPFClient.TicketBookingServiceReference.passengerDTO arg1) {
            WPFClient.TicketBookingServiceReference.BookFlightRequest inValue = new WPFClient.TicketBookingServiceReference.BookFlightRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).BookFlightAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFClient.TicketBookingServiceReference.loginResponse WPFClient.TicketBookingServiceReference.TicketBooking.login(WPFClient.TicketBookingServiceReference.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public WPFClient.TicketBookingServiceReference.passengerDTO login(string arg0, string arg1) {
            WPFClient.TicketBookingServiceReference.loginRequest inValue = new WPFClient.TicketBookingServiceReference.loginRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WPFClient.TicketBookingServiceReference.loginResponse retVal = ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).login(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.loginResponse> WPFClient.TicketBookingServiceReference.TicketBooking.loginAsync(WPFClient.TicketBookingServiceReference.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.loginResponse> loginAsync(string arg0, string arg1) {
            WPFClient.TicketBookingServiceReference.loginRequest inValue = new WPFClient.TicketBookingServiceReference.loginRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFClient.TicketBookingServiceReference.getAllFlightResponse WPFClient.TicketBookingServiceReference.TicketBooking.getAllFlight(WPFClient.TicketBookingServiceReference.getAllFlightRequest request) {
            return base.Channel.getAllFlight(request);
        }
        
        public WPFClient.TicketBookingServiceReference.flight[] getAllFlight() {
            WPFClient.TicketBookingServiceReference.getAllFlightRequest inValue = new WPFClient.TicketBookingServiceReference.getAllFlightRequest();
            WPFClient.TicketBookingServiceReference.getAllFlightResponse retVal = ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).getAllFlight(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.getAllFlightResponse> WPFClient.TicketBookingServiceReference.TicketBooking.getAllFlightAsync(WPFClient.TicketBookingServiceReference.getAllFlightRequest request) {
            return base.Channel.getAllFlightAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.getAllFlightResponse> getAllFlightAsync() {
            WPFClient.TicketBookingServiceReference.getAllFlightRequest inValue = new WPFClient.TicketBookingServiceReference.getAllFlightRequest();
            return ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).getAllFlightAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityResponse WPFClient.TicketBookingServiceReference.TicketBooking.findAllCountriesToWhichPlanesDepartFromAgivenCity(WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityRequest request) {
            return base.Channel.findAllCountriesToWhichPlanesDepartFromAgivenCity(request);
        }
        
        public WPFClient.TicketBookingServiceReference.countryDTO[] findAllCountriesToWhichPlanesDepartFromAgivenCity(string arg0, string arg1) {
            WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityRequest inValue = new WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityResponse retVal = ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).findAllCountriesToWhichPlanesDepartFromAgivenCity(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityResponse> WPFClient.TicketBookingServiceReference.TicketBooking.findAllCountriesToWhichPlanesDepartFromAgivenCityAsync(WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityRequest request) {
            return base.Channel.findAllCountriesToWhichPlanesDepartFromAgivenCityAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityResponse> findAllCountriesToWhichPlanesDepartFromAgivenCityAsync(string arg0, string arg1) {
            WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityRequest inValue = new WPFClient.TicketBookingServiceReference.findAllCountriesToWhichPlanesDepartFromAgivenCityRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).findAllCountriesToWhichPlanesDepartFromAgivenCityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFClient.TicketBookingServiceReference.findAirPortByCityResponse WPFClient.TicketBookingServiceReference.TicketBooking.findAirPortByCity(WPFClient.TicketBookingServiceReference.findAirPortByCityRequest request) {
            return base.Channel.findAirPortByCity(request);
        }
        
        public WPFClient.TicketBookingServiceReference.airport[] findAirPortByCity(string arg0) {
            WPFClient.TicketBookingServiceReference.findAirPortByCityRequest inValue = new WPFClient.TicketBookingServiceReference.findAirPortByCityRequest();
            inValue.arg0 = arg0;
            WPFClient.TicketBookingServiceReference.findAirPortByCityResponse retVal = ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).findAirPortByCity(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findAirPortByCityResponse> WPFClient.TicketBookingServiceReference.TicketBooking.findAirPortByCityAsync(WPFClient.TicketBookingServiceReference.findAirPortByCityRequest request) {
            return base.Channel.findAirPortByCityAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findAirPortByCityResponse> findAirPortByCityAsync(string arg0) {
            WPFClient.TicketBookingServiceReference.findAirPortByCityRequest inValue = new WPFClient.TicketBookingServiceReference.findAirPortByCityRequest();
            inValue.arg0 = arg0;
            return ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).findAirPortByCityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFClient.TicketBookingServiceReference.findAirPortByCountryResponse WPFClient.TicketBookingServiceReference.TicketBooking.findAirPortByCountry(WPFClient.TicketBookingServiceReference.findAirPortByCountryRequest request) {
            return base.Channel.findAirPortByCountry(request);
        }
        
        public WPFClient.TicketBookingServiceReference.airport[] findAirPortByCountry(string arg0) {
            WPFClient.TicketBookingServiceReference.findAirPortByCountryRequest inValue = new WPFClient.TicketBookingServiceReference.findAirPortByCountryRequest();
            inValue.arg0 = arg0;
            WPFClient.TicketBookingServiceReference.findAirPortByCountryResponse retVal = ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).findAirPortByCountry(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findAirPortByCountryResponse> WPFClient.TicketBookingServiceReference.TicketBooking.findAirPortByCountryAsync(WPFClient.TicketBookingServiceReference.findAirPortByCountryRequest request) {
            return base.Channel.findAirPortByCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findAirPortByCountryResponse> findAirPortByCountryAsync(string arg0) {
            WPFClient.TicketBookingServiceReference.findAirPortByCountryRequest inValue = new WPFClient.TicketBookingServiceReference.findAirPortByCountryRequest();
            inValue.arg0 = arg0;
            return ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).findAirPortByCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromResponse WPFClient.TicketBookingServiceReference.TicketBooking.findAllTheCountriesThatPlanesDepartFrom(WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromRequest request) {
            return base.Channel.findAllTheCountriesThatPlanesDepartFrom(request);
        }
        
        public WPFClient.TicketBookingServiceReference.countryDTO[] findAllTheCountriesThatPlanesDepartFrom() {
            WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromRequest inValue = new WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromRequest();
            WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromResponse retVal = ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).findAllTheCountriesThatPlanesDepartFrom(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromResponse> WPFClient.TicketBookingServiceReference.TicketBooking.findAllTheCountriesThatPlanesDepartFromAsync(WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromRequest request) {
            return base.Channel.findAllTheCountriesThatPlanesDepartFromAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromResponse> findAllTheCountriesThatPlanesDepartFromAsync() {
            WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromRequest inValue = new WPFClient.TicketBookingServiceReference.findAllTheCountriesThatPlanesDepartFromRequest();
            return ((WPFClient.TicketBookingServiceReference.TicketBooking)(this)).findAllTheCountriesThatPlanesDepartFromAsync(inValue);
        }
    }
}
